### ISSUE TITLE
Solution Please?  Error

### ISSUE THREAD

**Issue by scriptxd** [SIAMRAHMAN000/___SIAM___VIEW___TIK___#1]
OSError: dlopen failed: library 👉 "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/tls_client/dependencies/tls-client-arm64.so in namespace (default)

Solution please

Tried Termux non root & Ubuntu Same Problem...

Note: Installed all requirements

**Comment by SIAMRAHMAN000** [comment]
Your Device Was 32 bit !!

**Comment by scriptxd** [comment]
No 64 bit ubuntu & termux
