### ISSUE TITLE
Android setup?

### ISSUE THREAD

**Issue by scriptxd** [SIAMRAHMAN000/___SIAM___VIEW___TIK___#2]
Tutorial please

**Comment by SIAMRAHMAN000** [comment]
[1] INSTALL TERMUX 
[2] Run pkg update
[3] pkg install git
[4] pkg install python
***************************
Install This Python Tool Requirements :
Type This => pip install -r requirements.txt
And After Download All Required Modules 
====================================
                           RUN  THIS  TOOL
====================================

**Comment by scriptxd** [comment]
OSError: dlopen failed: library "libpthread.so.0" not found: needed by /data/data/com.termux/files/usr/lib/python3.11/site-packages/tls_client/dependencies/tls-client-arm64.so in namespace (default)
~/___SIAM___VIEW___TIK___ $

Failed to run this in termux
